### ISSUE TITLE
Is it possible to add a link to header tag as what hexo-renderer-marked did?

### ISSUE THREAD

**Issue by leonfancy** [wzpan/hexo-renderer-pandoc#38]
Is it possible to add a link to each header tag as what hexo-renderer-marked did here: https://github.com/hexojs/hexo-renderer-marked/blob/master/lib/renderer.js#L36

**Comment by Ritsuka314** [comment]
It is possible, but it is not what this plugin does. This plugin is only to bridge hexo and pandoc.

What you desire can be achieved by writing customized Pandoc filter. Please consult Pandoc's [documentation on filters](https://pandoc.org/filters.html).

As an example, a [project](https://github.com/RichardYan314/hexo-pandoc-tippy) of myself has a pandoc filter as part of it, written in python (`pandocFilter.py`). [This documentation section](https://github.com/RichardYan314/hexo-pandoc-tippy#installing) shows how to configure hexo to tell this plugin, which in turn tells pandoc to use that filter script.

Feel free to contact via my email listed on this website with further questions regarding pandoc filters. But as far as this project concerns, this issue is closed.

**Comment by seekstar** [comment]
I have written an npm package to make this easier: <https://github.com/seekstar/hexo-pandoc-header-anchor/>
