### ISSUE TITLE
'\oiint' could not show

### ISSUE THREAD

**Issue by HasegawaAzusa** [wzpan/hexo-renderer-pandoc#46]
'\oiint' could not show
![image](https://user-images.githubusercontent.com/34785132/159250387-25aa9e20-d650-42bc-9070-acf2a01ec905.png)

**Comment by ChenglinYu** [comment]
收到

**Comment by Ritsuka314** [comment]
Which math engine are you using? I know that MathJax does not support `\oiint` but am not sure about KaTeX.

You may want to consult this https://math.meta.stackexchange.com/questions/9973/how-do-you-render-a-closed-surface-double-integral

Anyway, this issue is not related to this plugin.

@ChenglinYu, I'd like to reiterate my earlier remark in case you haven't see it. Please refrain yourself from posting extraneous comments to the issue reports. Please correct me, but I don't recognize you being involved in the development of this plugin, so please do not reply 收到 to our issue reports, as it can be mistakenly interpreted by the reporters of the issues as that you acknoledge the issues on behalf of the development team. I will have to block your comment if you continue doing so. My kindest regrets.
