### ISSUE TITLE
Can I set the resource root path?

### ISSUE THREAD

**Issue by ytf4425** [wzpan/hexo-renderer-pandoc#52]
I use typora to write md file.

When I insert picture in my article xxx.md, typora will create a directory named xxx and put picture in it, then insert ![](xxx/yyy.png) in my article.

When I used [hexo-renderer-marked](https://github.com/hexojs/hexo-renderer-marked), I can write following config to make it generate the web page with picture url like http://example.com/xxx/yyy.png.

```
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
```

However, I have not found a way to set [hexo-renderer-pandoc](https://github.com/hexojs/hexo-renderer-pandoc) to use such a resource url. Now it generate the web page with picture url live http://example.com/xxx/xxx/yyy.png (a wrong path).

Now I use hexo-asset-img to solve it temporarily

**Comment by Ritsuka314** [comment]
My 2c: this seems to be a very useful feature that requires extensive efforts of possiblly writing a pandoc filter. It is possible to either implement the filter separate from this project or include it as part of this project. I'm in favour of the first possibility. If anyone is interested in the second please re-open the issue.

**Comment by Doublefire-Chen** [comment]
Same issue, I use hexo-renderer-pandoc to replace hexo-renderer-marked in order to gain LaTeX support. However, posts rendered by hexo-renderer-pandoc cannot show the images as it changes images paths. All my images are in domain/images, the hexo-renderer-pandoc use domain/{title}/images/image_filename. Maybe I can make a PR to solve this problem when I am free. Now I need to prepare my exam so I need to change back to hexo-renderer-marked temporarily.

**Comment by Doublefire-Chen** [comment]
> My 2c: this seems to be a very useful feature that requires extensive efforts of possiblly writing a pandoc filter. It is possible to either implement the filter separate from this project or include it as part of this project. I'm in favour of the first possibility. If anyone is interested in the second please re-open the issue.
> I'm in favour of the first possibility.

Have you find the proper filter to solve this problem?
